import Head from 'next/head';
import MainLayout from '../layouts/Main.layout';

const Index = () => {
	return (
		<>
			<Head>
				<title>Create Next App</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<main>
				<MainLayout>
					<h1>Hello World!</h1>
				</MainLayout>
			</main>
		</>
	);
};

export default Index;
