import Head from 'next/head';
import MainLayout from '../layouts/main/Main.layout';
import CenterCard from '../components/CenterCard/CenterCard';
import styles from './index.module.scss';
import { Box, Grid } from '@material-ui/core';

const Index = () => {
    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main>
                <MainLayout>
                    <CenterCard>
                        <>
                            <img src='/vector-musical_1.svg' alt='Stay tuned to positive!' />
                        </>
                    </CenterCard>
                    <Grid container justifyContent='center'>
                        <Box className={styles.background}>
                            <Box className={styles.mainText} textAlign='center'>
                                Here you can enjoy your favorite tracks without any ADs and other shit
                            </Box>
                        </Box>

                    </Grid>
                </MainLayout>
            </main>
        </>
    );
};

export default Index;
